#!/bin/sh
set -e

unlock_repo(){
  (
    cd "$1"
    if grep -q git-crypt .git/config; then
      echo "already unlocked $1"
      exit 0
    fi
    if [ -d .git-crypt/keys ]; then
      findargs="( $(gpg --list-secret-keys --with-colons| awk -F: '$1 == "sec" {print "-name *" $5 ".gpg"}' | sed -z 's/\n-/ -o -/g' ) )"
      [ -n "$findargs" ] || return 0
      if find .git-crypt/keys $findargs | grep -q "."; then
        echo "unlocking $1"
        git-crypt unlock
        return $?
      fi
    fi
    echo "no keys found for $1"
  )
}

inotifywait -m -e moved_to -r "$1" --format "%f %w" | while read file dir; do
  [ "$file" == "index" ] || continue
  echo "found $dir"
  git_dir=$(dirname $dir)
  unlock_repo "$git_dir"
done
